		<img src="img/wwfnepal/about-wwf-nepal<?php echo get_small_image();?>.jpg" class="hidden">
    	<div id="acknowledgement-popup" class="popup-wrap" style="background-image: url('img/wwfnepal/about-wwf-nepal<?php echo get_small_image();?>.jpg'); height: 100%; width: 100%; top: 0; left: 0; z-index: 999;">            
            <?php copyright('Robert Van Waarden/WWF');?>
    		<div class="scrollbar-outer-div">
            <div class="scrollbar-inner-div">
                <div class="scrollbar-div article-section">	        	
    				<?php popup_navigation();?>
	        		<div class="section-intro content-txt section-absolute box" style="background-color: #f8a681;">
		                <h1 class="uppercase">ACKNOWLEDGEMENTS</h1>
		                <p>WWF Nepal acknowledges with gratitude the support received from the following partners, donors and supporters:</p>
		                <ul class="list-disc">
		                    <li>Government of Nepal; National Planning Commission; Ministry of Finance; Ministry of Forests and Soil Conservation; Ministry of Population and Environment; Ministry of Culture, Tourism and Civil Aviation; Ministry of Agricultural Development; Ministry of Land Reform and Management; Ministry of Women, Children and Social Welfare; Department of National Parks and Wildlife Conservation; Department of Forests; Department of Plant Resources; Department of Forest Research and Survey; Department of Soil Conservation and Watershed Management; Water and Energy Commission Secretariat; Department of Hydrology and Meteorology; Nepal Tourism Board; Social Welfare Council; Alternative Energy Promotion Centre; Lumbini Development Trust.</li>
		                    <li>Ministry for Foreign Affairs of Finland; Embassy of the United States; Embassy of Finland; United States Agency for International Development; German Embassy; Department for International Development; Global Environment Facility; Australian Government/Department of Foreign Affairs and Trade; US Fish and Wildlife Service; Leonardo DiCaprio Foundation; World Bank; MyClimate; The Prince Albert II of Monaco Foundation; The Coca Cola Company; Google Foundation; Whiskas; Ms. Nancy Abraham; Trade Union Solidarity Centre of Finland; KfW Development Bank; International Union for Conservation of Nature; Intrepid Foundation; Hoffman La Roche; Sall Family Foundation.</li>
		                    <li>WWF US; WWF UK; WWF Finland; WWF International; WWF Netherlands; WWF Australia; WWF Canada; WWF Switzerland; WWF China; WWF Malaysia; WWF Singapore; WWF Austria; WWF Germany; WWF India; WWF Pakistan; WWF Bhutan; TRAFFIC; Asian Rhinos and Elephant Action Strategy; Living Himalayas Initiative; Tigers Alive Initiative.</li>
		                    <li>International Centre for Integrated Mountain Development; The World Conservation Union Nepal; CARE Nepal; International Water Management Institute; International Trust for Tiger Conservation.</li>
		                    <li>National Trust for Nature Conservation; Nepal Army; Nepal Police; Wildlife Conservation Nepal; Federation of Community Forestry Users, Nepal; Society of Hydrology and Meteorology-Nepal; Family Planning Association of Nepal; Dolphin Conservation Society; Environmental Camps for Conservation Awareness; Youth Alliance for Environment; Green Youth Lumbini; Nepal Forum for Environmental Journalists; Society of Environmental Journalists; Clean Energy Nepal; Biogas Sector Partnership Nepal; Tribhuvan University; Kathmandu University; Institute of Forestry; Wildlife Watch Group; Bird Conservation Nepal; National Environmental Coalition of Indigenous Nationalities; Ethnobotanical Society of Nepal; Wildlife Conservation Nepal; National Foundation for the Development of  Indigenous Nationalities; Building and Wood Workers’ International Nepal Affiliate Committee; Trade Union National Centres; School Environment Conservation Education Network Nepal; Nepal Foresters Association; Nepal Federation of Indigenous Nationalities; Himalayan Grassroots Women’s Natural Resource Management Association; Dalit Alliance for Natural Resources, Nepal; Centre for Rural Technology; Community-Based Forestry Supporters’ Network, Nepal; Center for Molecular Dynamics.</li>
		                </ul>
		                <p>WWF Nepal would  like to  express special thanks to: Community Based Organizations; Media; Community Forest Coordination Committees; Community Forest User Groups, Buffer Zone User Groups; Buffer Zone User Committees; Buffer Zone Management Committees; Community-Based Anti-Poaching Units; Eco Clubs; Ghodaghodi Area Conservation and Awareness Forum; Kangchenjunga Conservation Area Management Council and user committees; Integrated Resource Management Committees; Mothers’ Groups; Youth Clubs; District Development Committees; District Forest Offices; Village Development Committees; Women Awareness Groups and local communities.</p>
		            </div> <!-- /.section-intro -->
		        </div>
	        </div>
	        </div>
    	</div>